# Top-level configuration
name = "paper"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-10-01"
main = "./src/worker/index.ts"

# Add your Cloudflare account ID
account_id = "819f489cce282d37d17186d04be30a0d"

workers_dev = false

r2_buckets = [
  { binding = "R2", bucket_name = "paper" }
]

[observability]
enabled = true
head_sampling_rate = 1

[assets]
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*", "!/app/*", "!/login", "!/signup" ]
